// <auto-generated />
using System;
using Hotel_Reservations_Manager.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelReservationsManager.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20230323084607_HotelResManagerDb")]
    partial class HotelResManagerDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClientsReservation", b =>
                {
                    b.Property<int>("ClientsClientId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationsResId")
                        .HasColumnType("int");

                    b.HasKey("ClientsClientId", "ReservationsResId");

                    b.HasIndex("ReservationsResId");

                    b.ToTable("ClientsReservation");
                });

            modelBuilder.Entity("Hotel_Reservations_Manager.Model.Clients", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<bool>("Adult")
                        .HasColumnType("bit");

                    b.Property<string>("E_mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Hotel_Reservations_Manager.Model.Reservation", b =>
                {
                    b.Property<int>("ResId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResId"));

                    b.Property<bool>("All_inclusive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Arrival_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Breakfast")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Departure_date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("RoomsId")
                        .HasColumnType("int");

                    b.Property<string>("Usename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Hotel_Reservations_Manager.Model.Rooms", b =>
                {
                    b.Property<int>("RoomsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomsId"));

                    b.Property<bool>("Is_Available")
                        .HasColumnType("bit");

                    b.Property<double>("Price_Adult")
                        .HasColumnType("float");

                    b.Property<double>("Price_Child")
                        .HasColumnType("float");

                    b.Property<int>("RoomsCapacity")
                        .HasColumnType("int");

                    b.Property<string>("RoomsType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomsId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Hotel_Reservations_Manager.Model.Users", b =>
                {
                    b.Property<string>("EGN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("E_mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Hire_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is_active")
                        .HasColumnType("bit");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Release_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Second_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EGN");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClientsReservation", b =>
                {
                    b.HasOne("Hotel_Reservations_Manager.Model.Clients", null)
                        .WithMany()
                        .HasForeignKey("ClientsClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel_Reservations_Manager.Model.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationsResId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
